# Generated by Django 5.1.4 on 2026-06-18 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=200)),
                ('sub_module', models.CharField(blank=True, default='', max_length=200)),
                ('tc_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('preconditions', models.TextField(blank=True, default='')),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_test_cases', to='projects.project')),
            ],
            options={
                'db_table': 'business_test_cases',
                'ordering': ['module', 'sub_module', 'tc_id'],
                'unique_together': {('project', 'tc_id')},
            },
        ),
        migrations.CreateModel(
            name='AutomationTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('recorder', 'Recorder'), ('ai', 'AI Generated')], default='manual', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_test_cases', to='projects.project')),
                ('business_test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_mappings', to='testcases.businesstestcase')),
            ],
            options={
                'db_table': 'automation_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('navigate', 'Navigate'), ('click', 'Click'), ('fill', 'Fill'), ('select', 'Select'), ('upload', 'Upload'), ('wait', 'Wait'), ('verify_text', 'Verify Text'), ('verify_url', 'Verify URL'), ('verify_element', 'Verify Element'), ('screenshot', 'Take Screenshot')], max_length=20)),
                ('target', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('wait_timeout', models.IntegerField(default=30000, help_text='Timeout in milliseconds')),
                ('object_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_steps', to='objects.objectrepository')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.automationtestcase')),
            ],
            options={
                'db_table': 'automation_steps',
                'ordering': ['order'],
                'unique_together': {('test_case', 'order')},
            },
        ),
    ]
