# Generated by Django 5.1.4 on 2026-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcasegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtestcase',
            name='business_test_case',
        ),
        migrations.AlterField(
            model_name='testcasegroup',
            name='test_cases',
            field=models.ManyToManyField(blank=True, related_name='test_case_groups', to='testcases.automationtestcase'),
        ),
        migrations.DeleteModel(
            name='BusinessTestCase',
        ),
    ]
