# Generated by Django 5.1.4 on 2026-06-18 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('element_type', models.CharField(choices=[('button', 'Button'), ('input', 'Input'), ('select', 'Select'), ('link', 'Link'), ('text', 'Text'), ('image', 'Image'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('other', 'Other')], default='other', max_length=20)),
                ('locator_strategy', models.CharField(choices=[('css', 'CSS Selector'), ('xpath', 'XPath'), ('id', 'ID'), ('name', 'Name'), ('text', 'Text'), ('role', 'Role'), ('test_id', 'Test ID (data-testid)'), ('placeholder', 'Placeholder'), ('label', 'Label')], max_length=20)),
                ('locator_value', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_repository', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Object Repository',
                'db_table': 'object_repository',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
