# Generated by Django 5.1.4 on 2026-06-18 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_result', models.TextField()),
                ('actual_result', models.TextField()),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('console_logs', models.TextField(blank=True, default='')),
                ('network_logs', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='projects.environment')),
                ('execution_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_records', to='executions.executionrun')),
                ('failed_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_records', to='executions.executionstepresult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='projects.project')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='testcases.automationtestcase')),
            ],
            options={
                'db_table': 'failure_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
