# Generated by Django 5.1.4 on 2026-06-18 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, default='', max_length=1000)),
                ('data_type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=10)),
                ('generator', models.CharField(blank=True, help_text='Generator function name for dynamic data (e.g., random_email)', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='projects.project')),
            ],
            options={
                'db_table': 'test_data',
                'ordering': ['key'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
