# Generated by Django 5.1.4 on 2026-06-18 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('passed_steps', models.IntegerField(default=0)),
                ('failed_steps', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='projects.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='projects.project')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='testcases.automationtestcase')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execution_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStepResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=500)),
                ('expected', models.TextField(blank=True, default='')),
                ('actual', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='executions.executionrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='testcases.automationstep')),
            ],
            options={
                'db_table': 'execution_step_results',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('console_log', 'Console Log'), ('network_log', 'Network Log'), ('video', 'Video'), ('timeline', 'Timeline'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('execution_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='executions.executionrun')),
                ('step_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='executions.executionstepresult')),
            ],
            options={
                'db_table': 'artifacts',
                'ordering': ['created_at'],
            },
        ),
    ]
