"""
Playwright script generation service.
"""
import logging
from .models import AutomationTestCase, AutomationStep

logger = logging.getLogger(__name__)


class ScriptGeneratorService:
    """Generate Playwright Python scripts from automation test cases."""

    ACTION_TEMPLATES = {
        "navigate": '    await page.goto("{value}")',
        "click": '    await page.click(\'{target}\')',
        "fill": '    await page.fill(\'{target}\', "{value}")',
        "select": '    await page.select_option(\'{target}\', "{value}")',
        "upload": '    await page.set_input_files(\'{target}\', "{value}")',
        "wait": '    await page.wait_for_timeout({value})',
        "verify_text": '    await expect(page.locator(\'{target}\')).to_contain_text("{value}")',
        "verify_url": '    await expect(page).to_have_url("{value}")',
        "verify_element": '    await expect(page.locator(\'{target}\')).to_be_visible()',
        "screenshot": '    await page.screenshot(path="{value}")',
    }

    @classmethod
    def generate_script(cls, test_case: AutomationTestCase) -> str:
        """Generate a complete Playwright Python script."""
        steps = test_case.steps.all().order_by("order")
        if not steps.exists():
            return "# No steps defined for this test case."

        lines = [
            '"""',
            f"Auto-generated Playwright script for: {test_case.name}",
            f"Generated by AI Regression Testing Platform",
            '"""',
            "import asyncio",
            "from playwright.async_api import async_playwright, expect",
            "",
            "",
            f"async def test_{cls._sanitize_name(test_case.name)}():",
            '    """',
            f"    {test_case.description or test_case.name}",
            '    """',
            "    async with async_playwright() as p:",
            "        browser = await p.chromium.launch(headless=True)",
            '        context = await browser.new_context()',
            "        page = await context.new_page()",
            "",
        ]

        for step in steps:
            target = step.get_resolved_target() or ""
            value = step.value or ""

            # Add comment
            description = step.description or f"{step.get_action_display()}"
            lines.append(f"        # Step {step.order}: {description}")

            # Generate action code
            template = cls.ACTION_TEMPLATES.get(step.action, "")
            if template:
                code = template.format(target=target, value=value)
                lines.append(f"    {code}")
            else:
                lines.append(f"        # Unknown action: {step.action}")

            lines.append("")

        lines.extend([
            "        await context.close()",
            "        await browser.close()",
            "",
            "",
            f'asyncio.run(test_{cls._sanitize_name(test_case.name)}())',
        ])

        return "\n".join(lines)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Convert a test case name to a valid Python function name."""
        sanitized = "".join(c if c.isalnum() or c == "_" else "_" for c in name.lower())
        sanitized = sanitized.strip("_")
        if sanitized and sanitized[0].isdigit():
            sanitized = f"test_{sanitized}"
        return sanitized or "unnamed_test"

    @classmethod
    def generate_human_readable(cls, test_case: AutomationTestCase) -> list:
        """Generate human-readable step descriptions."""
        steps = test_case.steps.all().order_by("order")
        readable = []
        for step in steps:
            target = step.get_resolved_target() or ""
            value = step.value or ""
            description = cls._describe_step(step.action, target, value, step.description)
            readable.append({
                "order": step.order,
                "action": step.action,
                "description": description,
            })
        return readable

    @staticmethod
    def _describe_step(action, target, value, custom_desc):
        """Create a human-readable description of a step."""
        if custom_desc:
            return custom_desc

        descriptions = {
            "navigate": f"Navigate to {value}",
            "click": f"Click on '{target}'",
            "fill": f"Fill '{target}' with '{value}'",
            "select": f"Select '{value}' from '{target}'",
            "upload": f"Upload file '{value}' to '{target}'",
            "wait": f"Wait for {value}ms",
            "verify_text": f"Verify '{target}' contains text '{value}'",
            "verify_url": f"Verify URL is '{value}'",
            "verify_element": f"Verify element '{target}' is visible",
            "screenshot": f"Take screenshot",
        }
        return descriptions.get(action, f"{action}: {target} {value}")


